import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          style={{
            margin: 0,
            padding: 0,
            minHeight: "100vh",
            position: "relative",
            overflowX: "hidden",
          }}
        >
          {/* 🔥 BACKGROUND LOGO WATERMARK */}
          <div
            style={{
              position: "fixed",
              inset: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              pointerEvents: "none",
              zIndex: 0,
            }}
          >
            <img
              src="/logo.webp"
              alt="background logo"
              style={{
                width: "520px",
                height: "auto",
                objectFit: "contain",

                /* 🔥 MORE VISIBLE */
                opacity: 0.22,

                /* keep clarity */
                filter: "contrast(1.15) saturate(1.1) brightness(1)",

                /* slight professional feel */
                transform: "scale(1.05)",
              }}
            />
          </div>

          {/* PAGE CONTENT */}
          <div style={{ position: "relative", zIndex: 1 }}>
            <Toaster position="top-center" />
            <Navbar />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
